# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
imagefolder: "/img/"

# THEME-SPECIFIC CONFIGURATION
remote_theme: hyde

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
#highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

coderay:
  coderay_wrap:              div
  coderay_line_numbers:      inline
  coderay_line_number_start: 1
  coderay_tab_width:         4
  coderay_bold_every:        10
  coderay_css:               style

#gems: [jekyll_test_plugin, jekyll-json, jekyll-assets]

theme: jekyll-theme-cayman
