title: Sujay Pillai
email: sujayopillai@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  DockerCaptain, Sr. DevOps Engineer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://sujayopillai.com" # the base hostname & protocol for your site, e.g. http://example.com
imagefolder: "/img/"
twitter_username: sujaypillai
github_username:  sujaypillai
google_analytics: "UA-65644221-1"

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2

#paginate: 5
timezone: Asia/Kuala_Lumpur
paginate_path: /page/:num/
pagination:
  enabled: true
  per_page: 5
  permalink: '/:year/:month/:title/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: compressed
